### ISSUE TITLE
Running on PI

### ISSUE THREAD

**Issue by yellowmegaman** [pbernasconi/pi-lock#1]
Hello!! Got an issue with getting it to work =(

Please help.

~/pi/python $ sudo python readRFID.py 
Traceback (most recent call last):
  File "readRFID.py", line 3, in <module>
    from classes.classPermiso import *
  File "/home/pi/pi/python/classes/classPermiso.py", line 2, in <module>
    import piLock.configuration as conf
ImportError: No module named piLock.configuration

**Comment by pierinz** [comment]
Try replacing "import piLock.configuration as conf" with "import configuration as conf" in each file in /classes. I haven't a free raspberry to test now, but with this change it tries to open the serial port.

**Comment by yellowmegaman** [comment]
Thanks for reply! i've decided to test after i got my reader ( rfid ) from china. Best luck!

**Comment by pierinz** [comment]
Can I ask you which one you choose? I'm quite satisfied with the Olimex MOD-RFID125, but I'm still looking for something better for my own project.

**Comment by yellowmegaman** [comment]
Waiting for this http://www.ebay.com/itm/221441513730?ssPageName=STRK:MEWNX:IT&_trksid=p3984.m1497.l2649 to be delivered

**Comment by pbernasconi** [comment]
@yellowmegaman I used [a similar RFID reader](http://www.seeedstudio.com/depot/125Khz-RFID-module-UART-p-171.html?cPath=19_24), from seeedstudio.com. 

As a side note for the Pi-Lock project, I used a lot of SQLite tables and personalized code for various functions, so the overall project may be a bit bloated. If you need additional help let me know!

**Comment by yellowmegaman** [comment]
Thanks a bunch =)

**Comment by yellowmegaman** [comment]
Hello again =) Finally got it, and tried.

After changing piLock.configuration -> configuration this err was solved.

But next thing came:

" File "/home/pi/pi/python/configuration.py", line 38, in <module>
    RPIO.setwarnings(False)
NameError: name 'RPIO' is not defined"

after commenting out all 4 lines:

#RPIO.setwarnings(False)
#RPIO.setup(GREEN, RPIO.OUT)
#RPIO.setup(RED, RPIO.OUT)
#RPIO.setup(BLUE, RPIO.OUT)

Everything (maybe?) worked.

Now, executing "sudo python readRFID.py"
i get output:
######################
/home/pi/pi/python
/home/pi/pi/python/classes
/home/pi/pi/python/RFID_Lock.sqlite

101
Open: /dev/ttyAMA0
######################
is it ok? would like actually learn how to read and write rfid keys for starters.

Great many thanks in advance, espesially if u're holding some info in memory and got time to respond =)
